# Generated by Django 4.0.5 on 2022-07-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_activated',
            new_name='email_active',
        ),
    ]
