# Generated by Django 4.0.5 on 2022-07-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
